version: "3.9"

services:
  db:
    image: "postgres"
    restart: always
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
  server:
    build: .
    depends_on:
      - db
    command: sh -c "npm run migrate && npm run dev"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb?schema=public
    ports:
      - "5000:5000"
